### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lemezohaib** [Sushrut1101/GoFile-Upload#2]
Facing this issue while uploading
curl: (26) Failed to open/read local data from file/application

**Comment by sullyps** [comment]
[I submitted a PR that fixes this issue](https://github.com/Sushrut1101/GoFile-Upload/blob/be87e0f3e9a906cba48755188cb142507f403121/upload.sh)

**Comment by lemezohaib** [comment]
> [I submitted a PR that fixes this issue](https://github.com/Sushrut1101/GoFile-Upload/blob/be87e0f3e9a906cba48755188cb142507f403121/upload.sh)

Btw do you have any working script for pixel drain?

**Comment by sullyps** [comment]
> > [I submitted a PR that fixes this issue](https://github.com/Sushrut1101/GoFile-Upload/blob/be87e0f3e9a906cba48755188cb142507f403121/upload.sh)
> 
> 
> 
> Btw do you have any working script for pixel drain?

Haven't personally used it but [the CLI tool on this repo should work for uploading/downloading from pixeldrain](https://github.com/ManuelReschke/go-pd)

**Comment by lemezohaib** [comment]
> > > [I submitted a PR that fixes this issue](https://github.com/Sushrut1101/GoFile-Upload/blob/be87e0f3e9a906cba48755188cb142507f403121/upload.sh)
> > 
> > 
> > Btw do you have any working script for pixel drain?
> 
> Haven't personally used it but [the CLI tool on this repo should work for uploading/downloading from pixeldrain](https://github.com/ManuelReschke/go-pd)

I have a bash script for it but it's not working anymore
